version: '3.7'

services:
  main-application:
    image: garfdev/webare:latest
    env_file: ./.env
    restart: always
    volumes:
      - ./logs:/app/logs/
      - ./clinic:/app/.clinic
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
